### ISSUE TITLE
Task enunciate not picked up

### ISSUE THREAD

**Issue by kopernic-pl** [stoicflame/enunciate-gradle#1]
Hi, i have no enunciate task added to gradle project, Gradle 2.7, minimal example
build.gradle - in fresh empty directory
plugins {
    id 'java'
    id 'com.webcohesion.enunciate' version '2.0.0'
}

dependencies are downloaded, no task on tasks list after executing gradle tasks

Any idea what's wrong?
Mateusz

**Comment by stoicflame** [comment]
@jskovjyskebankdk, any ideas on this issue?

**Comment by stephannagy** [comment]
I see the same behavior in 2.6 as well.

**Comment by stephannagy** [comment]
I was seeing this earlier today, after restructuring my build file it started working.

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath group: 'gradle.plugin.com.webcohesion.enunciate', name: 'enunciate-gradle', version: '2.0.0'
  }
}
....
apply plugin: 'com.webcohesion.enunciate'

tasks.enunciate {
  configFileName = "enunciate.xml"
  File enunciateDistDir = file("src/main/webapp")
  include("**/*.java")
  export("docs", enunciateDistDir)
}
...
```

**Comment by jskov-jyskebank-dk** [comment]
As you found, you need to apply the plugin for the task to appear.

As for the plugins {} syntax not working (if that is what you saw), I can't really comment.

We use a Nexus as a proxy for Maven dependencies, and the gradle plugin repository cannot be proxied.
So we also have to manually add the plugins.gradle.org/m2 repository.
