### ISSUE TITLE
Updating build requirements or keeping them stable for now?!

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [stoicflame/enunciate-gradle#18]
Yesterday I made some commits to this project that will force - with next release - users to Java8 and a much newer Gradle.

On my way in to work this morning, I wondered if you (@stoicflame) would maybe have a say in this?
Maybe prefer to keep the requirements stable, until the rest of Enunciate goes Java8?

(I mean, if you make a 2.10.2 release, this change would take effect for the gradle plugin).

I am personally done with Java 7 and older Gradles. But my interests are different than what you may want to cater for with this project - and the Enunciate "brand".

I could fork the project, and maintain java8 changes (and a new feature) there.
And undo the changes on master.
If anyone would want to maintain the java7/gradle2 support, they could backport the changes from my fork.

What are your thoughts on this?

**Comment by stoicflame** [comment]
Enunciate 2.11 will include a requirement for Java 8, dropping support for Java 7, so I think we're aligned on timing on this. We'll just move forward saying Java 7 users will be stuck on Enunciate 2.10 until they update to Java 8.

**Comment by jskov-jyskebank-dk** [comment]
OK, I have landed the changes on master.

The Readme is updated to:
- Say that 2.11+ will require new java/gradle
- The two new documented features do not take effect until 2.11
