### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by mrgmatthews** [stoicflame/enunciate-gradle#2]
Not picking up the Javadoc for my descriptions in my multi poject gradle project

**Comment by mrgmatthews** [comment]
looked at the swagger.json and descriptions are not being populated there.
issue with the version of swagger being used?

**Comment by jskov-jyskebank-dk** [comment]
I wonder if this might be the sourcepath equivalent of the Ant Task?
That is not set in the Gradle plugin.

I guess that referenced project's sources should be added.

Also, I know that if the Eclipse plugin is used, it will cause source dependencies to be fetched as well.
Otherwise it is not (AFAIK) normal for Gradle to fetch source dependencies.
But if present, I guess they should be added as well.

I will see if I can find time to fix it this week.

**Comment by jskov-jyskebank-dk** [comment]
Not sure about the swagger.json thing. Paging @stoicflame

**Comment by mrgmatthews** [comment]
/**
- The main REST service for Project.
  *
- @author me
  */
  @Path(MyRestService.BASE)
  @GZIP
  public interface MyRestService {
  
  static final String BASE = "/1.0";
  static final String CREATE_DUDE = "/configuration/{customerId}/dude";
  
  @Path("/{path : .*}")
  @OPTIONS
  @GZIP
  Response options();
  
  /**
  - 
  - @param httpHeaders headers
  - @param customerId the id for the customer
  - @param dude the dude your submitting
  - @return a response is returned here
  - @throws Exception oh no could be a bad request
    */
    @Path(CREATE_DUDE)
    @POST
    @Consumes(APPLICATION_JSON)
    @Produces(APPLICATION_JSON)
    @GZIP
    Response createDude(@Context HttpHeaders httpHeaders, @PathParam("customerId") String customerId, @GZIP Dude dude) throws Exception;

}

This is roughly what I am doing, I would have expected the descriptions to come out from the JavaDoc

**Comment by mrgmatthews** [comment]
So i managed to solve this issue.
It was due to my configuration before I was using modules

``` xml
<modules>
<docs splashPackage="com.XXX" docsDir="api" title="XXX API" copyright="XXX" />
<basic-app disabled="false" />
<java-client disabled="false" />
<xml disabled="false" />
<jaxws-client disabled="false" />
<jboss disabled="false" />
<jaxws-ri disabled="false" />
<jaxws-support disabled="false" />
<csharp disabled="true" />
<jersey disabled="true" />
<c disabled="true" />
<obj-c disabled="true" />
</modules>
```

(DONT INCLUDE THE ABOVE IF YOU HAVE THE SAME ERROR)

This Im guessing caused the source to be replaced by the classes losing the javadoc info.

now I just do

``` xml
<api-classes>
        <include pattern="com.XXX.*"/>
    </api-classes>
```

and it all works fine. Hope this helps someone else
