### ISSUE TITLE
Error creating task

### ISSUE THREAD

**Issue by sadamyne** [stoicflame/enunciate-gradle#24]
Hi,

Im trying to create a task for running enunciate.
`buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.webcohesion.enunciate:enunciate-gradle:2.12.0"
  }
}

apply plugin: "com.webcohesion.enunciate"

tasks.enunciate {
  File enunciateDistDir = file("src/documentation")
  doFirst {
    enunciateDistDir.deleteDir()
    enunciateDistDir.mkdirs()
  }
  export("docs", enunciateDistDir)
}`
`task buildDocs(type: com.webcohesion.enunciate.EnunciateTask) {
    configFileName = "enunciate.xml"
    File enunciateDistDir = file("src/main/webapp")
    include("**/*.java")
    doFirst {
       enunciateDistDir.deleteDir()
        enunciateDistDir.mkdirs()
    }
    export("docs", enunciateDistDir)
}`

I get a 

> Cannot create task of type 'EnunciateTask' as it does not implement the Task interface.`
The tasks.enunciate is not working either, i can't get the documentation to go the desired folder.

Any ideia of waht Im i doing wrong?

Thanks in advance

**Comment by stoicflame** [comment]
I wish I knew Gradle better. @jskovjyskebankdk any ideas?

**Comment by jskov-jyskebank-dk** [comment]
Sorry, no idea.

Are you using a recent version of Gradle? I am using the latest version without problems.

**Comment by sadamyne** [comment]
Hi, im using 4.7.
I must be missing something obvious....

**Comment by jskov-jyskebank-dk** [comment]
I have information from #25 that allows me to reproduce, so follow updates there.
