### ISSUE TITLE
Java 7 gradle not working

### ISSUE THREAD

**Issue by sadamyne** [stoicflame/enunciate-gradle#26]
Hi,

I'm still struggling to get enunciate to work. (https://github.com/stoicflame/enunciate-gradle/issues/24#issuecomment-534185592)

I'm using Java 7, could this be the problem?
Thanks in advanced

**Comment by stoicflame** [comment]
Hello. So you're saying that the thread at #25 didn't help? Can you provide some way to reproduce the issue? Can you modify the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) in a way that exposes the problem?

**Comment by jskov-jyskebank-dk** [comment]
You may use java7 for your code. But you need java8 to drive Gradle and the Enunciate plugin.

If you already do that, please create the example project I asked for in #25.

**Comment by jskov-jyskebank-dk** [comment]
If you can provide a project demonstrating the problem, please reopen this bug.
