### ISSUE TITLE
unable to publish: multiple plugins are using the same ID

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate-gradle#28]
An attempt to publish the latest version 2.13.0 failed. I tried running `gradlew publishPlugins`.

@jskovjyskebankdk can you take a look? I don't do gradle, so I'm not sure what to do here.

```
Execution failed for task ':publishPlugins'.
> Invalid plugin ID 'com.webcohesion.enunciate': multiple plugins are using the same ID
```

**Comment by jskov-jyskebank-dk** [comment]
Hi Ryan!
I updated to latest Gradle version and tweaked the build file a little. It should work now (for me, at least as far as complaining about missing credentials for publishing).
