### ISSUE TITLE
Enunciate Task not working

### ISSUE THREAD

**Issue by baranidharan776** [stoicflame/enunciate-gradle#29]
Hi,
I created a task by following this plugin documentation and couldn't able to identify whether the enunciate task is triggered as folder is always empty. I don't see any example you provided for gradle in online.

Task :
`
tasks.enunciate {

    	File enunciateDistDir = file("C:/dev/docs/enunciate")
    	configFileName = "enunciate.xml"
       	export("docs", file(enunciateDistDir))
}
`

I can see this below log alone in console related to enunciate 

**Loading plugin enunciate from sample**

so i couldn't able to figure whether its working or not else where it went wrong.

Gradle Version : Gradle 5.5.1
Java Version : java version "1.8.0_241"

**Comment by jskov-jyskebank-dk** [comment]
Run with gradle -i to get some more logging.

That may help you find the problem.

**Comment by baranidharan776** [comment]
I have modified the gradle task as below 
`
 task restAPIDocsGeneration() {

    tasks.enunciate {
    	File enunciateDistDir = file("C:/dev/docs")
    	classpathConfigName	= "./build-tools/enunciatelib"
    	configFileName = "./enunciate.xml"
       	export("docs", file(enunciateDistDir))
    }
}
`
My file structure looks like below

Project
| build-tools/enunciatelib ( consist of jar related to enunciate)
| src/main/java
| enunciate.xml
| build.gradle

when i run the task in console as **gradle -i restAPIDocsGeneration**
It shows
> Task :restAPIDocsGeneration UP-TO-DATE
Skipping task ':restAPIDocsGeneration' as it has no actions.
:restAPIDocsGeneration (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.002 secs.

But i still seen the target folder is empty.

**Comment by stoicflame** [comment]
Thanks for looking at this @jskovjyskebankdk .

**Comment by jskov-jyskebank-dk** [comment]
The task name is enunciate. Note restAPIDocsGeneration.

**Comment by baranidharan776** [comment]
Thanks @jskovjyskebankdk . 

> Task :enunciate FAILED
Caching disabled for task ':enunciate' because:
  Build cache is disabled
Task ':enunciate' is not up-to-date because:
  No history is available.
Modules:
 com.webcohesion.enunciate.modules.java_xml_client.JavaXMLClientModule@5fcb9265
 com.webcohesion.enunciate.modules.idl.IDLModule@726580b8
 com.webcohesion.enunciate.modules.csharp_client.CSharpXMLClientModule@59b3176c
 com.webcohesion.enunciate.modules.jaxws.JaxwsModule@b7460f8
 com.webcohesion.enunciate.modules.c_client.CXMLClientModule@63ef1733
 com.webcohesion.enunciate.modules.objc_client.ObjCXMLClientModule@197a6d12
 com.webcohesion.enunciate.modules.php_xml_client.PHPXMLClientModule@1290c501
 com.webcohesion.enunciate.modules.jaxb.JaxbModule@25814439
 com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule@60440f4e
 com.webcohesion.enunciate.modules.php_json_client.PHPJSONClientModule@26db58a0
 com.webcohesion.enunciate.modules.ruby_json_client.RubyJSONClientModule@50257269
 com.webcohesion.enunciate.modules.javascript_client.JavaScriptClientModule@24176f80
 com.webcohesion.enunciate.modules.gwt_json_overlay.GWTJSONOverlayModule@c636bfa
 com.webcohesion.enunciate.modules.jackson.JacksonModule@2022dd42
 com.webcohesion.enunciate.modules.jackson1.Jackson1Module@be8e8e4
 com.webcohesion.enunciate.modules.jaxrs.JaxrsModule@42f7510
 com.webcohesion.enunciate.modules.docs.DocsModule@19af6d4e
 com.webcohesion.enunciate.modules.spring_web.SpringWebModule@13981f5f
 com.webcohesion.enunciate.modules.swagger.SwaggerModule@e4ce95d
:enunciate (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.553 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':enunciate'.
> Failed to invoke Enunciate

Could you help me to resolve this issue.

It will be much better if we got some tutorial or working demo of this enunciate gradle plugin

**Comment by jskov-jyskebank-dk** [comment]
Sorry, that is out of scope for what I am willing to do for you.

Search on github. I am sure you will find some example usages.
