### ISSUE TITLE
Objective-C libraries are not generated

### ISSUE THREAD

**Issue by Pscheidl** [stoicflame/enunciate-gradle#6]
Hello,
I'm using Enunciate gradle plugin to generate docs and java client. This worked well without any problems. However, I'd like to generate Objective C client too. I've enabled the module with         <obj-c disabled="false"/> - to no avail. When I enable all the plugins, only PHP, Java, Ruby and probably one other client is generated, but not the Objective C client. C# XML Client also doesn't work.

My enunciate settings:

```
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.2.0.xsd">

    <deployment protocol="https" host="xxx.com" context="/api"/>
    <title>Test environment</title>
    <modules>
        <c-xml-client disabled="true"/>
        <csharp-xml-client disabled="true"/>
        <jaxb disabled="true"/>
        <jackson disabled="false"/>
        <jackson1 disabled="true"/>
        <java-xml-client disabled="false"/>
        <java-client disabled="false"/>
        <spring-web disabled="true"/>
        <jaxws disabled="true"/>
        <gwt-json-overlay disabled="true"/>
        <obj-c-xml-client disabled="true"/>
        <obj-c disabled="false"/>
        <php-xml-client disabled="true"/>
        <php-json-client disabled="true"/>
        <ruby-json-client disabled="true"/>
        <idl disabled="true"/>
        <swagger disabled="false"/>
    </modules>
</enunciate>
```

Buildscript - gradle

```
buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:1.2.2"
        classpath "gradle.plugin.com.webcohesion.enunciate:enunciate-gradle:2.2.0"
    }
}
```

Some additional configuration

```

enunciate {
    configFileName = 'enunciate/enunciate.xml'
}

tasks.enunciate.doFirst { project.delete("build/enunciate") }
```

Thank you for any kind of help.

**Comment by stoicflame** [comment]
Objective-C (And C#, Java-XML) libraries are only generated when you have an XML API available. Enunciate doesn't (yet) have support for generating a JSON library for Objective-C. So since your API has no SOAP services, no classes annotated with `@XmlRootElement`, and no resources that produce XML, Enunciate doesn't know how to generate any Objective-C libraries for you.
